import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    absolute:'',
    default:'Ayushi layout',
    template: "%s | Next.js App",
  },
  description: "Generated by Next.js",
};

import Header from "./Header";
import Footer from "./Footer";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
